version: '2'
services:
  signature-verifier:
    image: ubirch/${project.artifactId}:${build.number}
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
      - "9010:9010"
    environment:
      KAFKA_URL: "kafka:9092"
      KAFKA_TOPIC_INCOMING_REQUESTS: "incoming"
      KAFKA_TOPIC_OUTGOING_VALID_REQUESTS: "outgoing"
      KAFKA_TOPIC_OUTGOING_INVALID_REQUESTS: "outgoing"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS_SEPARATOR: |
      KAFKA_CREATE_TOPICS: "incoming:1:1:delete,compact|outgoing:1:1:delete,compact"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
